### ISSUE TITLE
Private -> Public repo pre-flight checklist

### ISSUE THREAD

**Issue by greenie** [uswitch/ustyle#147]
- [x] Clean up CONTRIBUTING.md
- [x] Clean up icon-upgrade.md (if it needs to exist still, move it to icon docs).
- [x] Clean up bower.json and package.json ready for publishing to Bower and NPM(?).
- [x] Proofread all the docs. Add anything that's missing, fix typos, remove uSwitch specific stuff etc.
  - [ ] Add Illustrator export settings notes to icon docs.
- [x] Add uStyle logo.
- [ ] Abstract common functions in `styleguide.js`. Move `DSS` specific stuff to `dss-helper.js`.
- [x] Clean up styleguide CSS and JS.
- [x] Any final changes to styleguide design?
